BitGo/wallet-recovery-wizard

- package.json
> [BG-5830] Version bump to v1.2

- src/components/non-bitgo.js
https://bitgoinc.atlassian.net/browse/BG-10354
Let's have a non-bitgo recovery output a file instead of the raw hex, so it will work more seamlessly with DAI's tools.
> BG-10354 output file instead of raw hex

- package-lock.json
- package.json
https://bitgoinc.atlassian.net/browse/BG-9744
> BG-9744 bump version to v1.5.0

- src/App.css
- src/components/unsigned-sweep.js
- src/constants/coin-config.js
- src/constants/nav.js
- src/constants/tooltips.js
- src/views/dashboard/index.js
https://bitgoinc.atlassian.net/browse/BG-10112
Add ability to construct an unsigned sweep recovery
> BG-10112 add unsigned sweep functions

- config/webpack.config.dev.js
- package-lock.json
- package.json
- scripts/electron-wait-react.js
- scripts/start.js
- src/App.js
- src/components/ledger.js
- src/constants/ledger.js
- src/constants/nav.js
- src/constants/tooltips.js
- src/main.js
- src/services/ledger.js
Signed-off-by: Tyler Levine <tyler@bitgo.com>
> BG-6950: Add support for recovering segwit unspents from ledger wallets

- package-lock.json
- package.json
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
https://bitgoinc.atlassian.net/browse/BG-11214
> BG-11214 Add KeyIDs to unsigned sweep

- src/constants/coin-config.js
https://bitgoinc.atlassian.net/browse/BG-10379
This allows for XRP and XLM unsigned sweeps.
Includes updated BitGoJs
> BG-10379 xlm and xrp unsigned sweeps

- CODEOWNERS
https://bitgoinc.atlassian.net/browse/BG-11201
Adding a codeowners file
> BG-11201 add codeowners

- src/main.js
a CORS issue is preventing us from running some of the functions locally.
https://bitgoinc.atlassian.net/browse/BG-11198
> BG-11198 fix CORS issue

- package.json
- src/components/ledger.js
- src/constants/nav.js
https://bitgo.freshdesk.com/a/tickets/84051
Now we can recover Non-segwit funds from a ledger as well.
> BG-12407 recover non-segwit ledger

- package-lock.json
- package.json
- src/components/migrated-legacy.js
- src/constants/coin-config.js
- src/constants/nav.js
- src/constants/tooltips.js
- src/views/login/index.js
https://bitgoinc.atlassian.net/browse/BG-12345
Extend the Migrated-BCH tool to include BTG and BSV
> BG-12345 extend migrated bch tool

- README.md
- package-lock.json
[https://bitgoinc.atlassian.net/browse/BG-19100](https://bitgoinc.atlassian.net/browse/BG-19100)
I have made the following changes:
1) Update package-lock.json to reflect package.json.
2) Reverse engineered and figured out required dependencies to be installed on a MacOS machine in order to generate MacOS, Win32, and Linux debian release packages. These information were not documented anywhere, and nobody knew after Danny Diekroeger left.
There is currently no unit test for verifying the release. Below are the build log and generated artifacts on my MacOS laptop.
```
Jamess-MacBook-Pro:wallet-recovery-wizard jamesmn$ npm run make
> BitGoWalletRecoveryWizard@2.1.2 make /Users/jamesmn/git-repo/wallet-recovery-wizard
> export NODE_ENV=production && node scripts/build.js && electron-forge …
```
> BG-19100 Update package-lock.json and README.md to reflect required dependencies

- package-lock.json
- package.json
- src/components/cross-chain.js
> BG-21332 Fix UI precision error

- README.md
- package-lock.json
- resources/package.json
- scripts/package.sh
This will ensure that versions are consistent throughout the several
package.json files.
Closes Ticket: BG-22355
> Update package script with versioning

- package.json
> Bump sdk version to use blockstream for btc recovery

- src/constants/tooltips.js
- src/views/login/index.js
> Improve error message to include IP verification

- src/components/cross-chain.js
- src/components/unsupported-token.js
We have a compatibility bug from upgrading the electron version - saving file to a path no longer worked. This PR fixes it.
Ticket: BG-24478
> Fix save-file bug

- package-lock.json
- package.json
> Update SDK to the correct latest version

- package-lock.json
- package.json
- We added better crosschain recovery logging on the SDK side.
This PR pulls in the changes in SDK, bump the version in WRW
Ticket: BG-22261
> Bump SDK and WRW version

- .eslintrc.json
- .gitignore
- .prettierignore
- .prettierrc.yml
- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/components/cross-chain.js
- src/components/error-message.js
- src/components/form-components.js
- src/components/header.js
- src/components/main-nav.js
- src/components/migrated-legacy.js
- src/components/non-bitgo.js
- src/components/sidebar.js
- src/components/unsigned-sweep.js
- src/components/unsupported-token.js
- src/constants/coin-config.js
- src/constants/tooltips.js
- src/mock/dns/package.json
- src/registerServiceWorker.js
- src/utils.js
- src/views/dashboard/index.js
- src/views/login/index.js
6594d11
Run `npx prettier --write .`
Issue: BG-26587
edb7961
Add prettier
Spend less time fighting IntellJ settings
https://prettier.io/docs/en/index.html
Issue: BG-26587
b86f5dc
Add IntelliJ .iml file to .gitignore
> Add prettierjs

- package-lock.json
- package.json
> Update patch version for release

- package-lock.json
- package.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
This PR adds two fields to the WRW unsigned sweep and non-bitgo recovery functions, to allow users to specify the gas limit and gas price for ETH tx.
> Bg 24734 add custom gas price and limit to eth

- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
Set the correct default gas price and gas limit: 
gasPrice: 20000000000,
gasLimit: 500000,
Ticket: BG-24734
> Fix gas limit and gas price value

- package-lock.json
- package.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
Fix WRW frontend Box B error and use Gwei instead of Wei in ETH custom gas.
> Bg 29489 wrw eth errors

- DEVELOPER.md
- README.md
- resources/package.json
Add documentation for:
1) Steps to add support for new coins
2) What coins are currently supported and what are not
3) Description of each of WRW's feature.
And a small fix of the package.json file, since the version is outdated.
> Bg 31067 add documentation

- package-lock.json
- package.json
This PR fixes the issue of cross chain recovery of LTC -> BTC by upgrading the BitGoJS to latest version.
Ticket: BG-32738
> fix(wrw): upgrade to latest bitgojs version

- package-lock.json
- package.json
- resources/package.json
This PR updates the version of Wallet Recovery Wizard to 2.8.10
> chore(wrw): updated the version of wrw

- package-lock.json
- package.json
- resources/package.json
- src/components/unsigned-sweep.js
This PR fixes the issue of unsigned transaction recovery of EOS by upgrading the BitGoJS to latest version. 
userKeyID and backupKeyID fields have been added to the Unsigned Sweep Page for EOS 
BG-30012
> fix(wrw): solve issue of eos unsigned tx recovery

- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
- src/utils.js
Ticket: [BG-32038](https://bitgoinc.atlassian.net/browse/BG-32038)
This PR updates
* accountlib packages:
* @bitgo/account-lib@2.17.0
* bitgo@13.0.1-rc.8
* `gasPrice` parameter for ETH to `maxFeePerGas`
* Added `maxPriorityFeePerGas`
> fix(eth): update gasPrice according to LHF

- package-lock.json
- package.json
- resources/package.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
This PR adds maxFeePerGas and maxPriorityFeePerGas parameters in Non-BitGo recovery and Unsigned Sweep Recovery Page for ERC20 token
Ticket: BG-32038
> feat(wrw): add eip1559 gasfields in erc20 recovery

- README.md
ltc and dash for testnets is no longer supported. updating docs.
> docs(wrw): update testnet support for coins

- config/env.js
- src/components/unsigned-sweep.js
> feat(wrw): optimise gas limit estimation

- src/components/migrated-legacy.js
> fix(wrw): remove bsv paygo fees

- config/env.js
- src/components/unsigned-sweep.js
this commit fixes build issues
caused by the introduction of
alchemy api key variable
Ticket- BG-00000
> fix(wrw): fix build issues

- package.json
- resources/package.json
> chore(wrw): update wrw version to 3.1.2

- package-lock.json
- package.json
and update wrw version in package-lock.json
Ticket: BG-0000
> chore(wrw): add sodium to package json

- package-lock.json
- package.json
- resources/package.json
and update WRW version to 3.1.3
> Update SDK to hotfix v2

- src/containers/BuildUnsignedSweepCoin/AvalancheCForm.tsx
- src/containers/BuildUnsignedSweepCoin/BitcoinCashForm.tsx
- src/containers/BuildUnsignedSweepCoin/BitcoinForm.tsx
- src/containers/BuildUnsignedSweepCoin/Erc20TokenForm.tsx
- src/containers/BuildUnsignedSweepCoin/EthereumForm.tsx
- src/containers/BuildUnsignedSweepCoin/LitecoinForm.tsx
- src/containers/BuildUnsignedSweepCoin/RippleForm.tsx
- src/containers/BuildUnsignedSweepCoin/TronForm.tsx
- src/containers/NonBitGoRecoveryCoin/AvalancheCForm.tsx
- src/containers/NonBitGoRecoveryCoin/BitcoinCashForm.tsx
- src/containers/NonBitGoRecoveryCoin/BitcoinForm.tsx
- src/containers/NonBitGoRecoveryCoin/Erc20TokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/EthereumForm.tsx
- src/containers/NonBitGoRecoveryCoin/LitecoinForm.tsx
- src/containers/NonBitGoRecoveryCoin/RippleForm.tsx
- src/containers/NonBitGoRecoveryCoin/TronForm.tsx
- src/helpers/index.ts
TODO: test unsigned sweep flows without walletPassphrase.
> chore: cleanup copy

- EOS.md
> chore: update eos readme for kylin network

- package-lock.json
- package.json
New WRW release for doge support
Ticket: [BG-63822](https://bitgoinc.atlassian.net/browse/BG-63822)
> chore: new release for doge support

- src/containers/BuildUnsignedSweepCoin/EthereumForm.tsx
- src/containers/NonBitGoRecoveryCoin/EthereumForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
> feat(eth): support tss recoveries

- src/components/BackToHomeHelperText/BackToHomeHelperText.stories.tsx
- src/components/BackToHomeHelperText/BackToHomeHelperText.tsx
- src/components/BackToHomeHelperText/index.ts
- src/components/CoinsSelectAutocomplete/CoinsSelectAutocomplete.tsx
- src/containers/Login/Login.tsx
- src/containers/Login/LoginForm.tsx
- src/helpers/index.ts
Adds the helper text below the email field, similar to how other components have it listed.
> chore: add back to main menu component for login form

- package-lock.json
- package.json
> chore(wrw): new release

- src/containers/WrongChainRecovery/WrongChainRecovery.tsx
- src/helpers/config.ts
> fix(wrw): display not supported message when missing coin configs for WCR

- DEVELOPER.md
- scripts/docker-build.sh
> fix(wrw): improve build script to work more reliably

- src/components/WalletTypeSelect/WalletTypeSelect.tsx
- src/components/WalletTypeSelect/index.ts
- src/containers/App.tsx
- src/containers/EvmCrossChainRecoveryCoin/ColdWalletForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/CustodyWalletForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/EvmCrossChainRecoveryBaseForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/EvmCrossChainRecoveryCoin.tsx
- src/containers/EvmCrossChainRecoveryCoin/HotWalletForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/index.ts
- src/containers/EvmCrossChainRecoveryIndex/EvmCrossChainRecoveryIndex.tsx
- src/containers/EvmCrossChainRecoveryIndex/index.ts
- src/containers/EvmCrossChainRecoveryWallet/EvmCrossChainRecoveryWallet.tsx
- src/containers/EvmCrossChainRecoveryWallet/index.ts
- src/containers/Home.tsx
- src/helpers/config.ts
> feat: implement evm cross chain recovery for hot, cold, custody wallets

- package-lock.json
- package.json
> chore(wrw): new release support evm based cross chain recoveries

- src/components/WalletTypeSelect/WalletTypeSelect.tsx
- src/containers/EvmCrossChainRecoveryCoin/ColdWalletForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/CustodyWalletForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/EvmCrossChainRecoveryBaseForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/EvmCrossChainRecoveryCoin.tsx
- src/containers/EvmCrossChainRecoveryCoin/HotWalletForm.tsx
> fix: evm cross chain recovery form changes

- package-lock.json
- package.json
> chore(wrw): new release for ethw recoveries

- package-lock.json
- package.json
> chore(wrw): new release for atom support non-bitgo recovery

- package-lock.json
- package.json
bumping trx sdk to fix
recovery flow
TICKET: EA-124
> chore: bump trx sdk

- package.json
> chore: bump release

- electron/main/index.ts
- package-lock.json
- package.json
this fixes how we pass in avaxc snowtrace api token for
recoveries
Ticket: EA-537
> fix: setting snowtrace api token correctly for avaxc recovery

- package-lock.json
- package.json
release v4.13.0
Ticket: EA-537
> chore: release 4.14.0

- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/BuildUnsignedSweepCoin/CardanoForm.tsx
- src/containers/BuildUnsignedSweepCoin/SolanaForm.tsx
- src/helpers/config.ts
TICKET: [WP-62](https://bitgoinc.atlassian.net/browse/WP-62?atlOrigin=eyJpIjoiZjA0ZjJlYTMzODAzNDc5N2E1ZDk3OTE5ZTVmMjU1OGMiLCJwIjoiaiJ9)
[WP-62]: https://bitgoinc.atlassian.net/browse/WP-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(wrw): add unsigned sweep support for ada and sol

- package-lock.json
- package.json
this fixes an issue with recovery
unsigned json generation to multisig
addresses
Ticket: EA-124
> chore: bump avaxc sdk

- package.json
> chore: release 4.15.0

- src/containers/WrongChainRecovery/WrongChainRecoveryForm.tsx
> fix: cross-chain-recovery uses the correct copy for dest addr

- package.json
> chore: release 4.16.0

- src/helpers/config.ts
https://bitgoinc.atlassian.net/browse/WP-377
> fix(wp): fix prod config to use dot instead of tdot

- src/containers/NonBitGoRecoveryCoin/BitcoinForm.tsx
> feat(wrw): add api key in wrw bitcoin form

- package-lock.json
- package.json
> chore: release 4.17.0

- package-lock.json
- package.json
> chore: release 4.18.0

- package-lock.json
> chore: update lock files

- electron/main/index.ts
- electron/preload/index.ts
- electron/types.ts
- src/containers/BuildUnsignedConsolidation/BuildUnsignedConsolidationCoin.tsx
- src/containers/BuildUnsignedConsolidation/GenericEcdsaForm.tsx
- src/helpers/config.ts
- src/preload.d.ts
- src/utils/types.ts
Adding support for EdDSA recovery consolidations
for the following coins: Ada and Dot.
Ticket: WP-570
> feat: EdDSA Recovery Consolidation Support

- electron/main/index.ts
- src/containers/BuildUnsignedConsolidation/BuildUnsignedConsolidationCoin.tsx
- src/containers/BuildUnsignedConsolidation/SolForm.tsx
- src/helpers/config.ts
Add support for solana recovery consolidations with durable nonces.
Ticket: WP-570
> feat: Support Solana Recovery Consolidations

- src/containers/BuildUnsignedConsolidation/GenericEcdsaForm.tsx
> fix(WRW): fix mpc field language for consolidation recovery

- src/containers/BuildUnsignedConsolidation/SolForm.tsx
> fix(WRW): fix sol field language for consolidation recovery

- package-lock.json
- package.json
> chore: release 4.20.0

- package-lock.json
- package.json
> chore: release 4.22.0, update lock files

- DOT.md
- SOL.md
minor docs fixes
[WP-1331](https://bitgoinc.atlassian.net/browse/WP-1331)
[WP-1331]: https://bitgoinc.atlassian.net/browse/WP-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(docs): minor docs fixes

- src/components/FormikTextfield/FormikTextfield.tsx
- src/components/Textfield/Textfield.tsx
- src/containers/BuildUnsignedConsolidation/GenericEcdsaForm.tsx
- src/containers/BuildUnsignedConsolidation/SolForm.tsx
- src/containers/EvmCrossChainRecoveryCoin/HotWalletForm.tsx
- src/containers/NonBitGoRecoveryCoin/AvalancheCForm.tsx
- src/containers/NonBitGoRecoveryCoin/AvalancheCTokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/BitcoinABCForm.tsx
- src/containers/NonBitGoRecoveryCoin/BitcoinCashForm.tsx
- src/containers/NonBitGoRecoveryCoin/BitcoinForm.tsx
- src/containers/NonBitGoRecoveryCoin/CardanoForm.tsx
- src/containers/NonBitGoRecoveryCoin/CosmosForm.tsx
- src/containers/NonBitGoRecoveryCoin/DogecoinForm.tsx
- src/containers/NonBitGoRecoveryCoin/Erc20TokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/EthLikeForm.tsx
- src/containers/NonBitGoRecoveryCoin/EthereumWForm.tsx
- src/containers/NonBitGoRecoveryCoin/HederaForm.tsx
- src/containers/NonBitGoRecoveryCoin/LitecoinForm.tsx
- src/containers/NonBitGoRecoveryCoin/PolkadotForm.tsx
- src/containers/NonBitGoRecoveryCoin/PolygonForm.tsx
- src/containers/NonBitGoRecoveryCoin/RippleForm.tsx
- src/containers/NonBitGoRecoveryCoin/SolanaForm.tsx
- src/containers/NonBitGoRecoveryCoin/TronForm.tsx
- src/containers/WrongChainRecovery/WrongChainRecoveryForm.tsx
password fields should be type password and optionally show password
TICKET: WP-1340
https://github.com/BitGo/wallet-recovery-wizard/assets/56167866/df4a784e-8e5e-4713-ba91-9f78c448e94f
> chore: add password input field (WP-1340)

- ADA.md
added ADA broadcast readme
WP-1383
> docs(root): add ADA broadcast readme

- ADA.md
fixed ADA broadcast script
WP-0000
> docs(root): fix ADA broadcast script

- electron/main/index.ts
- scripts/build-icons.js
- src/components/CryptocurrencyIcon/CryptocurrencyIcon.tsx
- src/containers/BuildUnsignedSweepCoin/AlgorandForm.tsx
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/NonBitGoRecoveryCoin/AlgorandForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
- src/helpers/config.ts
> feat(wrw): add non-bitgo and unsigned sweep recovery for algo

- ETHLIKE.md
- README.md
This PR updates Readme files to add instructions to broadcast EthLike coins txs
WIN-2242
> docs: update readme to broadcast ethlike txs

- package-lock.json
- package.json
- src/containers/BroadcastTransactionCoin/BroadcastTransactionCoin.tsx
- src/containers/BuildUnsignedSweepCoin/AlgorandForm.tsx
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
> fix(wrw): add bitgoKey and pass nodeParams to broadcast for algo

- src/containers/EvmCrossChainRecoveryCoin/EvmCrossChainRecoveryCoin.tsx
- src/helpers/config.ts
> feat: add support for eth in evm ccr

- electron/main/index.ts
WIN-2611
This PR solves issue of arb and op token recoveries
> fix(wrw): fix issue with arb and op token recovery

- src/containers/WrongChainRecovery/WrongChainRecovery.tsx
> feat: allow api key in cross chain recovery page

- .github/workflows/release.yml
> fix: mac file name for release workflow

- .github/workflows/release.yml
> ci: pin the macos runner version

- .github/workflows/release.yml
This reverts commit 1a83911e88f15d648aa39fa11d79d141dc77e351.
> Revert "fix: mac file name for release workflow"

- electron/main/index.ts
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/BuildUnsignedSweepCoin/EthLikeTokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/EthLikeTokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
- src/helpers/config.ts
> feat: add WRW support for polygonToken

- src/helpers/index.ts
> fix(wrw): adding txBase64 to valid recovery check

- src/helpers/config.ts
> chore: add support opt chain for EVM CCR

- src/containers/EvmCrossChainRecoveryWallet/CustodyWalletForm.tsx
- src/containers/EvmCrossChainRecoveryWallet/EvmCrossChainRecoveryBaseForm.tsx
- src/containers/EvmCrossChainRecoveryWallet/EvmCrossChainRecoveryWallet.tsx
Ticket: COIN-597
Updated waller recovery form for custody wallet. It changes the form to consist of only 5 input fields.
> feat(wrw): update custody wallet recovery flow

- src/containers/BuildUnsignedConsolidation/BuildUnsignedConsolidationCoin.tsx
- src/containers/BuildUnsignedConsolidation/SolTokenForm.tsx
- src/helpers/config.ts
Ticket: COIN-874
token consolidation : https://explorer.solana.com/tx/7CmdZmqj62hdk1DVWe3eSryY8wnt9PpBMmupSP1f6pwiDh4NuCbPd22an7CZZRTH2vpVLbMB4VavXFoU1o9HVJ6?cluster=devnet
coin consolidation : https://explorer.solana.com/tx/61cA2TRetN9Fas1nA71qnCPaAWUZqHcub5rpQe4kF7K3NL3GveYrnzNq2T7yuYHhaVG7o9bsGXpQt4RVmmCDG6V9?cluster=devnet
> chore: take token contract as input in consolidation

- src/containers/BuildUnsignedConsolidation/BuildUnsignedConsolidationCoin.tsx
- src/containers/BuildUnsignedConsolidation/TronTokenForm.tsx
- src/helpers/config.ts
Token : https://shasta.tronscan.org/#/transaction/23ff340164bbd1a377417e7d05714170856f8193093cb63ed2fba06334672843
Coin : https://shasta.tronscan.org/#/transaction/8e58c8598ef22afdec57f7f15194ef761b5db0ab412882f46e3a3c0f0ef60a15
Ticket: COIN-890
> chore: trx token consolidation

- src/containers/EvmCrossChainRecoveryWallet/EvmCrossChainRecoveryBaseForm.tsx
- src/helpers/config.ts
Ticket: COIN-797
Earlier the evm ccr form has the same default gasLimit and fees for all coins. This change apply coin specific default values.
> feat(wrw): Apply coin specific gasLimit and fees for evm ccr form

- src/containers/BuildUnsignedSweepCoin/AlgorandForm.tsx
Fixes title from "Hot" -> "Cold" for unsigned sweep
> chore: fix algo unsigned sweep title

- AVAX-C.md
added avax-c broadcast tx readme
WP-2200
> docs(root): add avax-c broadcast tx readme

- src/helpers/config.ts
[COIN-1463](https://bitgoinc.atlassian.net/browse/COIN-1463)
[COIN-1463]: https://bitgoinc.atlassian.net/browse/COIN-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(wrw): add arb and op as intended chain for polygon

- electron/types.ts
- src/containers/BroadcastTransactionCoin/BroadcastTransactionCoin.tsx
- src/containers/BroadcastTransactionCoin/SuiForm.tsx
- src/helpers/config.ts
- src/utils/types.ts
Ticket: [WIN-3289](https://bitgoinc.atlassian.net/browse/WIN-3289)
[WIN-3289]: https://bitgoinc.atlassian.net/browse/WIN-3289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(sui): broadcast transaction

- electron/main/index.ts
- electron/preload/index.ts
- electron/types.ts
- src/containers/BuildUnsignedConsolidation/BuildUnsignedConsolidationCoin.tsx
- src/helpers/config.ts
- src/preload.d.ts
- src/utils/types.ts
Ticket: [WIN-3296](https://bitgoinc.atlassian.net/browse/WIN-3296)
[WIN-3296]: https://bitgoinc.atlassian.net/browse/WIN-3296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(sui): build unsigned consolidations

- src/helpers/config.ts
> feat(ccr): add polygon as intended chain for bsc

- src/helpers/config.ts
> feat(ccr): add intended chains for recovery on base chain

- src/containers/EvmCrossChainRecoveryWallet/EvmCrossChainRecoveryBaseForm.tsx
- src/helpers/config.ts
[COIN-1592](https://bitgoinc.atlassian.net/browse/COIN-1592)
[COIN-1592]: https://bitgoinc.atlassian.net/browse/COIN-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(wrw): add ccr support for arbeth

- src/containers/EvmCrossChainRecoveryWallet/EvmCrossChainRecoveryWallet.tsx
WRW : Removal of user key from the recovery file
> chore(wrw) : userKey removal from the recovery file generated.

- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/helpers/index.ts
> fix: handle duplicate token contract addresses

- src/helpers/config.ts
> chore: update testnet explorer URL for coredao

- .github/CODEOWNERS
> fix: restrict ownership of CODEOWNERS

- .github/CODEOWNERS
WIN-4914
Code owners have been updated to eth-alt as well as btc team.
> Code Owners change
