- README.md
- package.json
- src/components/sidebar.js
- src/main.js
Modifies package.json to use electron-forge dependencies and node scripts. Bumps version to 1.1.0. Removes unused package (dns) which was causing conflicts with forge, and replaces react-addons-css-transition-group with react-transition-group/CSSTransitionGroup.
> [BG-5339] Refactor executable bundling experience for WRW

- src/main.js
Window can now be resized to larger than the default size. This will be especially useful when the bulk wrong chain recovery PR is landed, as users may want to see all transaction IDs on one screen.
> [BG-5602] Make WRW window resizable

- src/components/cross-chain.js
- src/components/form-components.js
- src/components/non-bitgo.js
Adds realtime input validation to non-BitGo and cross-chain recoveries. Supports:
- Disabling whitespace on a field - whitespace is automatically removed on type or paste (useful for keycard values which preserve newlines)
- Enforcing numerical input - currently only used for address scanning factor
- Enforcing JSON object input - useful for keycard values, error text explains the format of a JSON object in simple terms
Also bumps reactstrap version to latest for some form eyecandy and modifies a couple of conventions
> [BG-5603] Realtime input validation

- src/components/unsupported-token.js
- src/constants/nav.js
- src/constants/tooltips.js
Adds a third recovery screen for recovering tokens that are not officially supported by BitGo. This process generates a half-signed Ethereum transaction to send the entire balance to a specified wallet address. This transaction is sent to support to be co-signed and broadcasted to the network.
> [BG-5601] Add unsupported cosigned token recovery

- package.json
- src/components/cross-chain.js
- src/components/form-components.js
- src/constants/tooltips.js
Adds a + button next to the txid field to add multiple txids. Multiple txids can be added or removed. If multiple transactions are needed, recovery transactions are saved in a zip file using jszip.
> [BG-5604] Add batching to cross-chain recovery

- .gitignore
- package.json
- src/App.js
- src/components/migrated-bch.js
- src/constants/nav.js
- src/constants/tooltips.js
- src/main.js
- src/views/login/index.js
Previously, support for recovering these types of wallets was only available via the bitgo-cli tool. While this works, it provides a user experience which leaves room for improvement.
> BG-8540: Add support for recovering migrated SafeHD BCH wallets

- src/components/form-components.js
- src/components/non-bitgo.js
https://bitgoinc.atlassian.net/browse/BG-10087
Currently we get an error when inputting an XLM key as the backup key, on an XLM recovery, even though that should be expected. The message says it expects an xpub, which is not true. It should expect an XLM pub key for XLM
> [BG-10087] XLM box B should expect XLM pub, not xpub

- src/constants/krs-providers.js
https://bitgoinc.atlassian.net/browse/BG-10871
Digital Asset "Services" is their new name
Also - not a bad idea to keep them as "dai" on the backend - we won't get confused with the other "DAS" that liquidity is working on
> BG-10871 change dai to das

- package-lock.json
- package.json
- src/components/unsupported-token.js
- src/constants/tooltips.js
https://bitgoinc.atlassian.net/browse/BG-11479
The WRW should be able to broadcast unsupported token recoveries without going through BitGo support. 
The reason is that currently, attempting to recover unsupported tokens from a live ETH wallet will mess up the the sequence ID's of the smart contract. By broadcasting from the WRW, we eliminate this issue. 
Tested locally by Danny
> BG-11479 fix unsupported erc-20 token recoveries

- package.json
https://bitgoinc.atlassian.net/browse/BG-11084
Now that we have the ledger tool's prebuilt binaries, we have to build the Mac dmg on a Mac machine, the Windows exe on a Windows machine, and the Linux .deb on a Linux machine.
This PR updates the build script to include the linux option, and it also separates the Mac/Windows build into two separate commands.
> BG-11084 update build scripts

- src/components/migrated-legacy.js
As part of https://bitgoinc.atlassian.net/browse/BG-12345
We need to handle tainted inputs and not sign them
> BG-12345 handle bsv taint

- package.json
Currently the WRW release process creates a 64-bit windows
application. This PR changes that to 32-bit to make it
compatible with both 32 and 64-bit architecture
Ticket: BG-17573
> Make release compatible with 32bit windows

- src/components/cross-chain.js
- src/components/migrated-legacy.js
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/components/unsupported-token.js
BitGoJS now uses _env instead of env, and also has
a new function getEnv() that should be used when possible.
This updates the WRW to properly use these
Ticket: BG-18417
> Fix env usage issues in BitGoJS

- README.md
- package.json
- src/constants/krs-providers.js
As part of my departure, I want to get WRW into
a good state. Let's get it to the latest bitgojs
which will fix a BTG recovery error. This PR
also adds Release info to the Readme and fixes the
name of Coincover
Ticket: BG-18467
> Upgrade bitgojs, improve docs, fix Coincover

- package-lock.json
- package.json
- src/components/non-bitgo.js
- src/constants/tooltips.js
Etherscan now requires an API key for Mainnet requests. This PR adds an extra input box for ETH and tokens so users can provide their own key.
Support can generate them too and provide them to the customer if needed, but they are free and have a limit of 5 requests per second/ip.
I tested this works with a Prod wallet I just created.
> BG-21679 Add etherscan API token field

- package-lock.json
- package.json
- resources/electron.js
The electron version in WRW is too old to be compatible an SDK that has higher version. We cannot bump the sdk version without upgrading the WRW itself.
- also fixed the BrowserWindow function in electron.js
for compatibility with the newer versions
Ticket: BG-24037
> Upgrade electron version to the latest:9.2.1

- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/tooltips.js
- src/utils.js
For non-BitGo recoveries (non-BitGo and unsigned sweep), we add a new field on the UI to accept a blockchair API key for bitcoin Mainnet and testnet recoveries.
I just tested that this worked for a btc prod wallet.
This change depends on the sdk change here: [https://github.com/BitGo/BitGoJS/pull/868](url)
> BG-24608 Accept API Key in non-BitGo Recovery and Unsigned Sweep

- package-lock.json
- package.json
A new version of SDK is used in the WRW, which now uses blockchair for bitcoin recovery and accepts an api key. So we need to bump the version of WRW. I made the WRW update a minor update, instead of a patch, since we are using a new API and does take in one more parameter to perform recovery.
These changes work locally. `npm start` runs the app properly.
> BG-24111: Bump WRW version

- src/components/unsigned-sweep.js
- src/constants/tooltips.js
Ticket: BG-24094
Same as [BG-21679,](https://github.com/BitGo/wallet-recovery-wizard/pull/78/files) we need to accept an etherscan token for unsigned-sweep too.-
> Add etherscan token field to unsigned sweep

- package.json
We fixed the [bug](https://github.com/BitGo/wallet-recovery-wizard/pull/91/files) that happened when trying to save transaction file for cross-chain recovery. Now bumping the version for a release. 
Ticket: BG-24516
> Bump patch version for bug fix

- package-lock.json
- package.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/coin-config.js
- src/constants/tooltips.js
This PR adds mainnet support for BSV recoveries. The SDK component has been implemented here [https://github.com/BitGo/BitGoJS/pull/890](url)
> BG-15531: Support bsv for non bitgo recoveries

- package.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/constants/coin-config.js
- src/constants/tooltips.js
We now use blockchair as an explorer for BCH as well, so we need to add the API key field and remove support for testnet, since blockchair does not support BCH testnet.
Ticket: BG-24863
> Add apiKey param and remove Testnet for BCH

- package-lock.json
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/utils.js
- Some of our v1 user key have key paths that are different from
our default key path for v2 keys, and they have addresses that are
currently un-derivable, with our current assumption of user 
key path. We add a helper function that keeps an array of possible
key paths to try from, with some alternatives, in case the default key 
path was not used when the key was generated
- Pulled out the `recover` logic from `unsigned-sweep` and `non-bitgo`
to the helper function above, reducing duplicate code
- this PR depends on https://github.com/BitGo/BitGoJS/pull/917, so
please review that PR first. 
- This PR also updates the SDK and WRW versions
Ticket: BG-24941
> Add alternative userKey path to query addresses from

- src/constants/coin-config.js
Per me and @barathcj 's discussion on the Friday WRW sync:
Our cross-chain recovery feature doesn't work well for BSV, and we are planning to shut down BSV as well. We should remove this feature from the WRW so clients don't get the false impression that they could rely on WRW for the faulty transactions they make.
Ticket: BG-25981
> Remove cross-chain recoveries related to BSV

- src/components/header.js
The method is deprecated in new react versions
https://reactjs.org/docs/react-component.html#mounting
Since we are not doing async operations we can just use the regular
constructor.
Tested login on local machine.
Issue: BG-26587
> header: remove componentWillMount

- src/App.js
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/utils.js
bf9f64c (Otto Allmendinger, 12 days ago)
Rename to copyDebugInfo()
Make `error` optional.
Issue: BG-26842
e94b7e3 (Otto Allmendinger, 12 days ago)
App reformat
For some reason IntelliJ insists on that order
Issue: BG-26842
2ad51ca (Otto Allmendinger, 13 days ago)
Add "copy error info" button
Copies error info to clipboard.
Reorganize code a bit to have `try {}` block smaller.
Issue: BG-26842
c83a77f (Otto Allmendinger, 13 days ago)
Add getEmptyState()
Make it easier to modify initial state.
d4fbc8f (Otto Allmendinger, 13 days ago)
Add getRecoveryDebugInfo()
45e25dc (Otto Allmendinger, 13 days ago)
Simplify recoverWithKeyPath
eeaa137 (Otto Allmendinger, 13 days ago)
logToConsole: use `console.error()`
b39b65c (Otto Allmendinger, 13 days ago)
Add `getBitgoInstanceFromEnv()`
Allows more …
> Add separate button "Copy Debug Info"

- src/constants/coin-config.js
- src/utils.js
As mentioned in the comment [here](https://github.com/BitGo/wallet-recovery-wizard/pull/107#issuecomment-744068568), the use of 'instanceOf' does not actually help us check the desired class, this blocked us from using the debugging button.
Tested locally, producing results like:
```
{
"errorMessage": "",
"errorStack": "",
"recoveryDebugInfo": {
"publicKeys": [
"xpub661MyMwAqRbcF6sE6BCY67SNEuGZQz9SEb2McBTYizUm27KwW11k6HcwRvAPHUPLaFVceZgYntaCLe5NFnRKa6QTuZNxAWK3txkiEeXLLfD",
"xpub661MyMwAqRbcFmjpPybTDabAqT52gVrYtUnhD7sawgmuSjGFKBuvYkQ8CUo6g3116RqS1vmzmhruLyy7K9VKm9dY4H75dGSGB5xUWTUYiYh",
"xpub661MyMwAqRbcG4N1kvajvzz61aRzA2kddX6pTbrbYKqnvqg42NDKEMQuCGf3XuVUEUHkX11bs1fJ4Lec8e1YHTtL5pLvRHsBuFgMAaPRhtP"
]
}
}
```
Ticket: BG-27474
> Fix issues with "instanceOf"

- DEVELOPER.md
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- resources/package.json
- scripts/package.sh
- src/components/non-bitgo.js
- src/components/unsigned-sweep.js
- src/utils.js
- src/views/login/index.js
Related Ticket: https://bitgoinc.atlassian.net/browse/BG-32964
Originally, when trying to upgrade to the latest version of Bitgo, we run into this build error where one of the node_modules (including bitgo) uses syntax from [ES2019](https://2ality.com/2017/08/optional-catch-binding.html).  
```
node_modules/@hashgraph/cryptography/src/primitive/hmac.browser.js
Module parse failed: Unexpected token (38:12)You may need an appropriate loader to handle this file type.
|             await window.crypto.subtle.sign("HMAC", key_, value)|         );
|     } catch {
|         throw new Error("Fallback if SubtleCrypto fails is not implemented");
|     }
```
I know Babel 7 has presets that allow you to transpile ES2019; I could not figure out how to do it on Babel 6, so I upgraded to Babel 7 and …
> fix(WRW): now can use latest BitgoJS version

- src/components/migrated-legacy.js
We just emit a generic error here without any info on what actually went
wrong. This should help users diagnose bad password errors easier.
Ticket: BG-33301
> fix(wrw): log underlying error when getting v1 signing keychain fails

- src/components/unsigned-sweep.js
This PR adds userKeyID and backupKeyID fields during the unsigned sweep recovery for ERC20 token
Ticket: BG-30057
> fix(wrw): add userkeyid during erc20 unsigned sweep recovery

- EOS.md
- README.md
- package-lock.json
- package.json
- resources/package.json
**Background**
EOS Jungle2.0 testnet got upgraded to EOS Jungle3.0 and in the process, its chain id also got changed. We had not updated this chain id. Because of this, we were facing issues while broadcasting the recovery transaction generated using Wallet Recovery Wizard (Non-Bitgo Recovery) as the chain id is being used in its generation.
**Changes**
- Fixed the issue of non-bitgo recovery of EOS by upgrading the BitGoJS to the latest version.
- Updated documentation for how to power up the eos account for broadcasting tx on the eos network
Ticket: BG-30012
> fix(wrw): fix eos testnet tx recovery issue

- package-lock.json
- package.json
- resources/package.json
- src/components/unsigned-sweep.js
- src/utils.js
since wallets can be created with user and backup keys
with custom derivation paths, we will need to give info
on which derivation path were used for each key so that
ovc which is only aware of master keys can properly use
the correct derivation path while signing
Ticket: BG-45944
> fix(wrw): Output xpubs with key derivation info if present

- src/components/unsigned-sweep.js
make  xpubsWithDerivationPath as the key instead of keys for xpub array to avoid collision with algo based keys.
Ticket: BG-45944
> fix(wrw): change xpub object key

- package-lock.json
- package.json
- src/components/migrated-legacy.js
- src/components/unsigned-sweep.js
These dependencies are outdated and cause issues when trying to build
releases.
If I understand correctly, because of the way the package-lock.json has been manually edited, it must be installed with `npm ci` for it to avoid the dependency issues.
Ticket: BG-48164
> fix(wrw): remove bitgo-utxo-lib and blake2b dependencies

- package-lock.json
- package.json
The latest version of the SDK includes these two PRs we need to resolve two cross chain recovery issues.
[fix: v1 getWallet call by DariusParvin · Pull Request #2289 · BitGo/BitGoJS](https://github.com/BitGo/BitGoJS/pull/2289) 
[fix(bitgo): getUnspentInfo to handle missing unspents by DariusParvin · Pull Request #2292 · BitGo/BitGoJS](https://github.com/BitGo/BitGoJS/pull/2292)
I've tested this package update (using `npm ci`) on mac and it fixed the issues.
Ticket: BG-48707
> chore(wrw): update sdk to hotfix.1

- electron/main/index.ts
- package-lock.json
- package.json
- src/components/CoinsSelectAutocomplete/CoinsSelectAutocomplete.tsx
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
- src/helpers/index.ts
Add support to ETHw to unsigned-sweep and non-bitgo. ETHw is to support an eventual PoW fork of ETH after the merge. Trying to recover it will fail for now since ETHw chain id is not confirmed neither there is a block explorer url.
BG-55419
> feat(wrw): add ethw to unsigned-sweep and non-bitgo

- src/helpers/index.ts
> fix: display friendly error message for request source unverified

- src/containers/BuildUnsignedSweepCoin/BitcoinForm.tsx
> feat(wrw): add api key in bitcoin unsigned sweep form

- electron/main/index.ts
- electron/preload/index.ts
- electron/types.ts
- src/components/Filefield/Filefield.tsx
- src/components/Filefield/index.ts
- src/components/FormikFilefield/FormikFilefield.tsx
- src/components/FormikFilefield/index.ts
- src/containers/App.tsx
- src/containers/CreateBroadcastableTransaction/CreateBroadcastableTransactionIndex.tsx
- src/containers/CreateBroadcastableTransaction/index.ts
- src/containers/Home.tsx
- src/preload.d.ts
- src/utils/types.ts
- When MPC recovery transactions are signed in OVC, they are not in a broadcastable state. This pr enables the user to transform their signed tx into a broadcastable tx.
Ticket: WP-470
> feat: Create Broadcastable Txs from Signed MPC Tx

- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/BuildUnsignedSweepCoin/CardanoForm.tsx
- src/containers/BuildUnsignedSweepCoin/SolanaForm.tsx
- src/containers/NonBitGoRecoveryCoin/CardanoForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
- src/containers/NonBitGoRecoveryCoin/PolkadotForm.tsx
- src/containers/NonBitGoRecoveryCoin/SolanaForm.tsx
- src/helpers/index.ts
- src/preload.d.ts
This PR changes the tss coins recovery form formats to conform to the new format specified by the recovery methods in the SDK.
Did the following E2E testing for these changes (for all 3 coins - SOL, DOT, ADA):
- Base Address - Non-Bitgo Recovery
- Base Address - Unsigned Sweep
- Base Address - Unsigned Sweep - Same Keys but Different Seed
TICKET: WP-588
**Non-Bitgo Recovery - Solana:**
**Non-Bitgo Recovery - Cardano:**
**Non-Bitgo Recovery - Polkadot:**
**Unsigned Sweep Recovery:**
> feat(WRW): change tss coins recovery form format

- src/containers/BuildUnsignedSweepCoin/AvalancheCForm.tsx
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/NonBitGoRecoveryCoin/AvalancheCForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
Since the external fullnode previously used, Snowtrace, was deprecated and replaced by the avax network, the recovery forms must be updated. The only difference is that there is no longer an API key, and updates in WRW must be made based on this. Changes have been tested e2e.
TICKET: WP-1135
> feat: update native avaxc recovery forms

- electron/main/index.ts
- src/containers/BuildUnsignedSweepCoin/AvalancheCTokenForm.tsx
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/NonBitGoRecoveryCoin/AvalancheCTokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
- src/helpers/config.ts
- src/preload.d.ts
TICKET: WP-885
tested recoveries, check ticket for details
a item in the list is added for AVAXC token and the inputs include the token contract address (similar to erc20)
> feat: add avaxc token support

- package-lock.json
- package.json
Older utxo-lib is used when compared to abstract-utxo dep. This causes version mistach issue that fails tbtc non bitgo recovery. Ticket: BTC-773
> chore(deps): bump mimtaching utxo lib

- .github/workflows/release.yml
- package-lock.json
- package.json
This PR adds a workflow that automates the releases to GitHub. The workflow is manually triggered, and the next semantic version must be provided when triggering the workflow. The new release will be left as a draft after the workflow has completed, so that the repo maintainer can review the release and publish it. No new commit will be pushed by the release workflow, and the new git tag will be created by GitHub when creating the new release.
I still need to update the release documentation in `DEVELOPER.md`, but I think this can happen in a future PR, after I have tested the new workflow against the master branch.
> feat: automate the releases

- .github/workflows/release.yml
jq will return `null` by default, but we were testing for an empty string instead.
> fix: default to empty string instead of null

- .github/workflows/release.yml
- package-lock.json
- package.json
I'm also switching to using `npm ci` which will rely on the versions locked in the package-lock file, to improve reproducibility even further.
Ticket: VL-1652
> feat: pin version of dmg-license

- .github/workflows/playwright.yml
- .github/workflows/storybook.yml
- .github/workflows/vitest.yml
This will make sure that the node version is in sync in all the GHA workflows.
> feat: use nvmrc node version in gha

- electron/main/index.ts
- electron/preload/index.ts
- src/containers/BuildUnsignedSweepCoin/AvalancheCTokenForm.tsx
- src/containers/BuildUnsignedSweepCoin/BuildUnsignedSweepCoin.tsx
- src/containers/BuildUnsignedSweepCoin/Erc20TokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/AvalancheCTokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/Erc20TokenForm.tsx
- src/containers/NonBitGoRecoveryCoin/NonBitGoRecoveryCoin.tsx
- src/preload.d.ts
renamed tokenAddress to tokenContractAddress since tokenAddress is not an param for the sdk recover method
WP-1221
[AVAXC testnet token recovery tx:](https://testnet.snowtrace.io/tx/0x3eecb54ddb15c61537c8e54e4138a0190cc7c84d41f43c4418644e6904a947f2?chainId=43113)
[ETH Holesky token recovery tx](https://holesky.beaconcha.in/tx/0x401c74b60c2cbc9f6f8d8aadcb68c4e0e875517b8ae2b008e44dfae57e8861c1)
> refactor(root): rename tokenAddress to tokenContractAddress

- package.json
Apparently, `electron-builder` will change the default `--publish` behavior when running from the `master` branch in GitHub Actions ([see this thread](https://github.com/electron-userland/electron-builder/issues/1693)), and will try to publish a draft release after building the project. This is not wanted, since we will publish the artifact later in the workflow when we have all the artifacts available.
> fix: do not publish using electron-builder

- .github/workflows/release.yml
This is just a copy-pasta from another workflow which I used as a template.
> fix: rename release workflow

- package-lock.json
- package.json
This fixes the critical VM2 dependency vulnerability.
DO-5208
> chore: update @bitgo/sdk-api to latest

- src/helpers/config.ts
Ticket: COIN-837
avaxc and etc are v0 wallets and we are recovering them via single sig.
> fix: remove avaxc and etc from intended chain

- electron/main/index.ts
- package-lock.json
- package.json
This PR unblocks recovery for ECDSA tss coins. A recent SDK change requires openSSLBytes to be dependency injected into the recover method.
In future prs we will remove opensslbytes all together from the TSS recovery flow.
> fix: DI openSSLBytes
